
ALTER TABLE public.club_messages
  ADD COLUMN IF NOT EXISTS reply_to_id UUID REFERENCES public.club_messages(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS is_edited BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS caption TEXT;
